version: "3"
services:
  nginx:
    image: hatiolab/operato-nginx:0.1
    ports:
      - ${HostPort}:80
    depends_on:
      - app
  app:
    container_name: operato-ecs
    image: hatiolab/operato-ecs:0.1
    volumes:
      - ./db.sqlite:/app/db.sqlite
    ports:
      - 3000